### ISSUE TITLE
Sign up Error

### ISSUE THREAD

**Issue by taiwoayanleye** [craftykate/odin-project#1]
Hi Kate,
Signup returns heroku error.
:)

**Comment by craftykate** [comment]
@TaiwoAyanleye: For the Hartl Sample App? Or another one? If it's the Hartl one, you can't sign up because I didn't bother to configure emails on Heroku. According to the code, the site sends a confirmation email - when it can't do that it throws an error. So I said on the site that you can't actually sign up. BUT, the code works, so if you take the code as an example it all runs the way it should, and works locally, so I can see that it does do what it's supposed to if there are email capabilities. You can **sign in** to the app on heroku though. Use `example@railstutorial.org` as the email and `foobar` as the password. 

If that's the one you're talking about I'll make it clearer that you can't sign up. 

Thanks for the feedback!

**Comment by taiwoayanleye** [comment]
It works. Should close this now. 
Thanks Kate!

**Comment by craftykate** [comment]
Thanks for letting me know about the confusion. I added the log in credentials to the README with a note there as well that you can't sign in because Heroku isn't set up to send out emails. I appreciate you letting me know about this!
